BEGIN TRANSACTION;

CREATE TABLE "municipios" (
	`MUNICIPIO_ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`NOME`	VARCHAR(50) NOT NULL,
	`ID` INTEGER NOT NULL,
	`ESTADO_ID`	INTEGER NOT NULL,
	`CODIGO`	INTEGER NOT NULL,
	`LONGITUDE`	REAL NOT NULL,
	`LATITUDE`	REAL NOT NULL,
	`ALTITUDE`	REAL NOT NULL
);


CREATE TABLE "estados" (
	`ESTADO_ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`NOME`	CHAR(20) NOT NULL,
	`SIGLA`	CHAR(2) NOT NULL,
	`REGIAO`	CHAR(13) NOT NULL
);

INSERT INTO `estados` VALUES(0,'RONDÔNIA','RO','Norte');
INSERT INTO `estados` VALUES(1,'ACRE','AC','Norte');
INSERT INTO `estados` VALUES(2,'AMAZONAS','AM','Norte');
INSERT INTO `estados` VALUES(3,'RORAIMA','RR','Norte');
INSERT INTO `estados` VALUES(4,'PARÁ','PA','Norte');
INSERT INTO `estados` VALUES(5,'AMAPÁ','AP','Norte');
INSERT INTO `estados` VALUES(6,'TOCANTINS','TO','Norte');
INSERT INTO `estados` VALUES(7,'MARANHÃO','MA','Nordeste');
INSERT INTO `estados` VALUES(8,'PIAUÍ','PI','Nordeste');
INSERT INTO `estados` VALUES(9,'CEARÁ','CE','Nordeste');
INSERT INTO `estados` VALUES(10,'RIO GRANDE DO NORTE','RN','Nordeste');
INSERT INTO `estados` VALUES(11,'PARAÍBA','PB','Nordeste');
INSERT INTO `estados` VALUES(12,'PERNAMBUCO','PE','Nordeste');
INSERT INTO `estados` VALUES(13,'ALAGOAS','AL','Nordeste');
INSERT INTO `estados` VALUES(14,'SERGIPE','SE','Nordeste');
INSERT INTO `estados` VALUES(15,'BAHIA','BA','Nordeste');
INSERT INTO `estados` VALUES(16,'MINAS GERAIS','MG','Sudeste');
INSERT INTO `estados` VALUES(17,'ESPÍRITO SANTO','ES','Sudeste');
INSERT INTO `estados` VALUES(18,'RIO DE JANEIRO','RJ','Sudeste');
INSERT INTO `estados` VALUES(19,'SÃO PAULO','SP','Sudeste');
INSERT INTO `estados` VALUES(20,'PARANÁ','PR','Sul');
INSERT INTO `estados` VALUES(21,'SANTA CATARINA','SC','Sul');
INSERT INTO `estados` VALUES(22,'RIO GRANDE DO SUL','RS','Sul');
INSERT INTO `estados` VALUES(23,'MATO GROSSO DO SUL','MS','Centro-Oeste');
INSERT INTO `estados` VALUES(24,'MATO GROSSO','MT','Centro-Oeste');
INSERT INTO `estados` VALUES(25,'GOIÁS','GO','Centro-Oeste');
INSERT INTO `estados` VALUES(26,'DISTRITO FEDERAL','DF','Centro-Oeste');

COMMIT;
